new_task:
  description: Adds a new task to the default list
  fields:
    task_title:
      description: "The task title"
      example: 'New Task'
    due_date:
      example: '2023-03-26'
      
complete_task:
  description: Marks a task as complete on a task list
  fields:
    task_title:
      example: 'Tasks to complete'
    task_list:
      example: 'Tasks list'
